"""add description and image url

Revision ID: 5789a94e3fd2
Revises: 04dce52d2230
Create Date: 2024-07-10 10:31:47.494197

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5789a94e3fd2'
down_revision = '04dce52d2230'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('image_url', sa.String(), nullable=True))
    op.add_column('pets', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'description')
    op.drop_column('pets', 'image_url')
    # ### end Alembic commands ###
