"""useser id

Revision ID: 58ac84899d92
Revises: cac283150fd8
Create Date: 2024-07-11 18:53:37.671198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58ac84899d92'
down_revision = 'cac283150fd8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('pets', sa.Column('user_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('pets', 'user_id')
    # ### end Alembic commands ###
